name: CI
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
jobs:
  parsing:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Parsing
        run: './ci/check-nix-files.sh'
      - name: ENVIRONMENTING
        run: 'nix --version'
      - name: ENVIRONMENTING1
        run: 'nix show-config'
  build:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Build
        run: 'nix-build'
  black:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Black
        run: './ci/check-formatting.sh'
  nixfmt:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Nix Format
        run: './ci/check-nix-formatting.sh'
  mypy:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Mypy
        run: './ci/check-mypy.sh'
  flake8:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Flake8
        run: './ci/check-flake8.sh'
  mypy-ratchet:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Mypy Ratchet
        run: './ci/mypy-ratchet.sh'
  coverage:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Coverage
        run: './ci/check-tests.sh'
  docs:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        # To use nixFlake in the next step
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Restructured Text Lint
        run: 'nix-shell --run "nix build .#checks.x86_64-linux.doc --experimental-features \"nix-command flakes\""'
      - name: build
        run: 'nix-build -A docs.x86_64-linux'
  poetry-up-to-date:
    strategy:
      fail-fast: false
      matrix:
        nix_path: [
            "nixpkgs=channel:nixos-unstable"
          , "nixpkgs=channel:nixos-20.09"
          , "nixpkgs=channel:nixos-20.03"
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Nix
        uses: cachix/install-nix-action@v14.1
        with:
          nix_path: ${{ matrix.nix_path }}
      - uses: cachix/cachix-action@v10
        with:
          name: nixops-digitalocean
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Prefetch shell.nix
        run: 'nix-shell --run true'
      - name: Poetry Locks Consistent
        run: './ci/check-poetry.sh'
